export { default as Home } from './Home'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Blog } from './Blog'
export { default as BlogPost } from './BlogPost'
export { default as WhyChooseUs } from './WhyChooseUs'
export { default as OurPrograms } from './OurPrograms'
